export interface PaymentAppConfig {
  provider: string;
  label: string;
  installedOnTestPhone: boolean;
  launchUrl: string | null;
  paymentFlowUrl: string | null;
  androidPackage: string | null;
  playStoreUrl: string;
  canOpenApp: boolean;
  canDeepLinkToPaymentFlow: boolean;
  canReceiveQrPayload: boolean;
  canReceiveAmount: boolean;
  fallbackBehavior: string;
  validationNote: string;
}

const PLAY_SEARCH_BASE = 'https://play.google.com/store/search?q=';
const PLAY_DETAILS_BASE = 'https://play.google.com/store/apps/details?id=';

function searchUrl(query: string): string {
  return `${PLAY_SEARCH_BASE}${encodeURIComponent(query)}&c=apps`;
}

export const PAYMENT_APP_CONFIG: Record<string, PaymentAppConfig> = {
  mercadopago: {
    provider: 'mercadopago',
    label: 'Mercado Pago',
    installedOnTestPhone: true,
    launchUrl: 'mercadopago://home',
    paymentFlowUrl: 'mercadopago://qr',
    androidPackage: 'com.mercadopago.wallet',
    playStoreUrl: `${PLAY_DETAILS_BASE}com.mercadopago.wallet`,
    canOpenApp: true,
    canDeepLinkToPaymentFlow: true,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Mercado Pago QR scanner and show merchant/amount in Paga Menos for manual confirmation.',
    validationNote: 'Pixel 8a package resolver accepts mercadopago://qr; no verified public intent was found for passing the scanned QR payload or amount.',
  },
  modo: {
    provider: 'modo',
    label: 'MODO',
    installedOnTestPhone: false,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: 'ar.com.modo',
    playStoreUrl: searchUrl('MODO'),
    canOpenApp: false,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Google Play if MODO is selected but not installed.',
    validationNote: 'Standalone MODO was not installed on the connected phone.',
  },
  naranjax: {
    provider: 'naranjax',
    label: 'Naranja X',
    installedOnTestPhone: true,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: 'com.tarjetanaranja.ncuenta',
    playStoreUrl: searchUrl('Naranja X'),
    canOpenApp: true,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Naranja X and show merchant/amount in Paga Menos for manual confirmation.',
    validationNote: 'Pixel 8a package launcher opens Naranja X, but nx://qr-payments-v2/screen and nx://home require DEEPLINK_PERMISSION from external callers; no verified payload or amount prefill contract was found.',
  },
  bbva: {
    provider: 'bbva',
    label: 'BBVA Argentina',
    installedOnTestPhone: true,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: 'com.bbva.nxt_argentina',
    playStoreUrl: searchUrl('BBVA Argentina'),
    canOpenApp: true,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open BBVA and show the QR details for manual payment.',
    validationNote: 'Pixel 8a resolver accepts BBVA app launch and real www.modo.com.ar/pagar/* links into BBVA, but Paga Menos cannot safely synthesize a bank payment link or amount.',
  },
  uala: {
    provider: 'uala',
    label: 'Uala',
    installedOnTestPhone: false,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: null,
    playStoreUrl: searchUrl('Uala'),
    canOpenApp: false,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Google Play if Uala is selected but not installed.',
    validationNote: 'Uala was not part of the requested installed-method set on the connected phone.',
  },
  personalpay: {
    provider: 'personalpay',
    label: 'Personal Pay',
    installedOnTestPhone: true,
    launchUrl: 'ar.com.personalpay://',
    paymentFlowUrl: null,
    androidPackage: 'ar.com.personalpay',
    playStoreUrl: searchUrl('Personal Pay'),
    canOpenApp: true,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Personal Pay and show merchant/amount in Paga Menos for manual QR payment.',
    validationNote: 'Pixel 8a resolver accepts ar.com.personalpay:// app launch; no QR/payment deep link was exposed in the package manifest.',
  },
  cuentadni: {
    provider: 'cuentadni',
    label: 'Cuenta DNI',
    installedOnTestPhone: false,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: null,
    playStoreUrl: searchUrl('Cuenta DNI'),
    canOpenApp: false,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Google Play if Cuenta DNI is selected but not installed.',
    validationNote: 'Cuenta DNI was not installed on the connected phone.',
  },
  ypf: {
    provider: 'ypf',
    label: 'YPF',
    installedOnTestPhone: false,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: null,
    playStoreUrl: searchUrl('YPF'),
    canOpenApp: false,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Google Play if YPF is selected but not installed.',
    validationNote: 'Not part of the requested payment-phone method list.',
  },
  shellbox: {
    provider: 'shellbox',
    label: 'Shell BOX',
    installedOnTestPhone: false,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: null,
    playStoreUrl: searchUrl('Shell BOX'),
    canOpenApp: false,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Google Play if Shell BOX is selected but not installed.',
    validationNote: 'Not part of the requested payment-phone method list.',
  },
  carrefour_bank: {
    provider: 'carrefour_bank',
    label: 'Banco Carrefour',
    installedOnTestPhone: true,
    launchUrl: 'com.carrefour.bancadeserviciosfinancieroscarrefour://',
    paymentFlowUrl: null,
    androidPackage: 'com.carrefour.bancadeserviciosfinancieroscarrefour',
    playStoreUrl: searchUrl('Carrefour'),
    canOpenApp: true,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Banco Carrefour and show merchant/amount in Paga Menos for manual payment.',
    validationNote: 'Pixel 8a resolver accepts app launch; no QR or amount handoff contract was exposed.',
  },
  bna: {
    provider: 'bna',
    label: 'BNA+',
    installedOnTestPhone: true,
    launchUrl: 'bnamas://',
    paymentFlowUrl: null,
    androidPackage: 'com.banconacion.bnamas',
    playStoreUrl: searchUrl('BNA+'),
    canOpenApp: true,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open BNA+ and show merchant/amount in Paga Menos for manual QR payment.',
    validationNote: 'Pixel 8a resolver accepts bnamas:// launch; no QR payload or amount handoff contract was exposed.',
  },
  bancon: {
    provider: 'bancon',
    label: 'Bancon',
    installedOnTestPhone: true,
    launchUrl: 'bancor://',
    paymentFlowUrl: null,
    androidPackage: 'ar.com.bancor.bancon',
    playStoreUrl: searchUrl('Bancon Bancor'),
    canOpenApp: true,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Bancon and show merchant/amount for manual payment.',
    validationNote: 'Pixel 8a resolver accepts bancor:// and real bancon.bancor.com.ar/modo/* links, but Paga Menos cannot safely synthesize a bank payment link or amount.',
  },
};

export function getPaymentAppConfig(provider: string): PaymentAppConfig {
  return PAYMENT_APP_CONFIG[provider] ?? {
    provider,
    label: provider,
    installedOnTestPhone: false,
    launchUrl: null,
    paymentFlowUrl: null,
    androidPackage: null,
    playStoreUrl: searchUrl(provider),
    canOpenApp: false,
    canDeepLinkToPaymentFlow: false,
    canReceiveQrPayload: false,
    canReceiveAmount: false,
    fallbackBehavior: 'Open Google Play or search for the selected payment app.',
    validationNote: 'No app capability entry has been validated for this provider.',
  };
}
